# Generated by Django 3.2.7 on 2023-05-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistapp', '0002_auto_20230520_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlistapp.streamplatform'),
            preserve_default=False,
        ),
    ]
