# Generated by Django 3.2.7 on 2023-06-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistapp', '0005_review_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
    ]
